sudo: false
language: java
jdk:
  - oraclejdk8
env:
  - TESTFOLDER=cdi
  - TESTFOLDER=security
  - TESTFOLDER=servlet
  - TESTFOLDER=jpa
  - TESTFOLDER=jsf
  - TESTFOLDER=jsonb
  - TESTFOLDER=validation

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn --batch-mode --fail-at-end --projects $TESTFOLDER -U --also-make-dependents install 2>&1 
